# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bolts_number.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_boltsNumber(object):
    def setupUi(self, boltsNumber):
        boltsNumber.setObjectName("boltsNumber")
        boltsNumber.resize(800, 600)
        boltsNumber.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(boltsNumber)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 80, 181, 71))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.kH = QtWidgets.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.kH.setFont(font)
        self.kH.setObjectName("kH")
        self.gridLayout_11.addWidget(self.kH, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.kgs = QtWidgets.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.kgs.setFont(font)
        self.kgs.setObjectName("kgs")
        self.gridLayout_10.addWidget(self.kgs, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_10, 0, 1, 1, 1)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.force = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.force.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.force.setObjectName("force")
        self.gridLayout_12.addWidget(self.force, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_12, 1, 0, 1, 2)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(50, 150, 181, 61))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.tmin = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.tmin.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tmin.setObjectName("tmin")
        self.gridLayout_2.addWidget(self.tmin, 1, 0, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(50, 220, 181, 61))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.diameter = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.diameter.setObjectName("diameter")
        self.gridLayout_3.addWidget(self.diameter, 1, 0, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(50, 460, 181, 61))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.number = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.number.setObjectName("number")
        self.gridLayout_4.addWidget(self.number, 1, 0, 1, 1)
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(50, 280, 181, 61))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 0, 0, 1, 1)
        self.strength = QtWidgets.QComboBox(self.gridLayoutWidget_5)
        self.strength.setObjectName("strength")
        self.gridLayout_5.addWidget(self.strength, 1, 0, 1, 1)
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(50, 340, 181, 61))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 0, 0, 1, 1)
        self.accuracy = QtWidgets.QComboBox(self.gridLayoutWidget_6)
        self.accuracy.setObjectName("accuracy")
        self.gridLayout_6.addWidget(self.accuracy, 1, 0, 1, 1)
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(50, 400, 181, 61))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 0, 0, 1, 1)
        self.mark = QtWidgets.QComboBox(self.gridLayoutWidget_7)
        self.mark.setObjectName("mark")
        self.gridLayout_7.addWidget(self.mark, 1, 0, 1, 1)
        self.gridLayoutWidget_8 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(240, 80, 200, 141))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        font2 = QtGui.QFont()
        font2.setBold(True)
        font2.setWeight(75)
        font2.setPointSize(12)
        self.label_8.setFont(font2)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_8.setObjectName("label_8")
        self.gridLayout_8.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_9.setFont(font2)
        self.label_9.setLineWidth(1)
        self.label_9.setMidLineWidth(0)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_8.addWidget(self.label_9, 1, 0, 1, 1)
        self.result = QtWidgets.QLabel(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.result.setFont(font)
        self.result.setAlignment(QtCore.Qt.AlignCenter)
        self.result.setText("")
        self.result.setObjectName("result")
        self.gridLayout_8.addWidget(self.result, 2, 0, 1, 1)
        self.pushResult = QtWidgets.QPushButton(self.gridLayoutWidget_8)
        self.pushResult.setObjectName("pushResult")
        self.gridLayout_8.addWidget(self.pushResult, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 50, 201, 28))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(470, 40, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayoutWidget_12 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_12.setGeometry(QtCore.QRect(450, 400, 301, 120))
        self.gridLayoutWidget_12.setObjectName("gridLayoutWidget_12")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.gridLayoutWidget_12)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_12)
        font1 = QtGui.QFont()
        font1.setBold(True)
        font1.setWeight(75)
        self.label_14.setFont(font1)
        self.label_14.setObjectName("label_14")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.gridLayout_15.addWidget(self.label_14, 0, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_12)
        font1 = QtGui.QFont()
        font1.setBold(True)
        font1.setWeight(75)
        self.label_15.setFont(font1)
        self.label_15.setObjectName("label_15")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.gridLayout_15.addWidget(self.label_15, 1, 0, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_15, 0, 0, 1, 1)
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_12)
        font1 = QtGui.QFont()
        font1.setBold(True)
        font1.setWeight(75)
        self.label_18.setFont(font1)
        self.label_18.setObjectName("label_18")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.gridLayout_16.addWidget(self.label_18, 1, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_12)
        font1 = QtGui.QFont()
        font1.setBold(True)
        font1.setWeight(75)
        self.label_16.setFont(font1)
        self.label_16.setObjectName("label_16")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.gridLayout_16.addWidget(self.label_16, 0, 0, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_16, 0, 0, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_14, 0, 1, 1, 1)
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.nb = QtWidgets.QLabel(self.gridLayoutWidget_12)
        self.nb.setFont(font)
        self.nb.setText("")
        self.nb.setAlignment(QtCore.Qt.AlignCenter)
        self.nb.setObjectName("nb")
        self.gridLayout_17.addWidget(self.nb, 0, 0, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_17, 1, 1, 1, 1)
        self.nbt = QtWidgets.QLabel(self.gridLayoutWidget_12)
        self.nbt.setFont(font)
        self.nbt.setText("")
        self.nbt.setAlignment(QtCore.Qt.AlignCenter)
        self.nbt.setObjectName("nbt")
        self.gridLayout_13.addWidget(self.nbt, 1, 0, 1, 1)
        self.gridLayoutWidget_18 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_18.setGeometry(QtCore.QRect(450, 250, 141, 81))
        self.gridLayoutWidget_18.setObjectName("gridLayoutWidget_18")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.gridLayoutWidget_18)
        self.gridLayout_19.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget_18)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_19.addWidget(self.label_24, 1, 0, 1, 1)
        self.distance_l = QtWidgets.QLineEdit(self.gridLayoutWidget_18)
        self.distance_l.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.distance_l.setObjectName("distance_l")
        self.gridLayout_19.addWidget(self.distance_l, 2, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_18)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_19.addWidget(self.label_21, 0, 0, 1, 1)
        self.gridLayoutWidget_17 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_17.setGeometry(QtCore.QRect(610, 110, 141, 121))
        self.gridLayoutWidget_17.setObjectName("gridLayoutWidget_17")
        self.gridLayoutWidget_19 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_19.setGeometry(QtCore.QRect(450, 110, 141, 121))
        self.gridLayoutWidget_19.setObjectName("gridLayoutWidget_19")
        self.twoimg = QtWidgets.QPushButton(self.centralwidget)
        self.twoimg.setGeometry(QtCore.QRect(600, 100, 150, 150))
        self.twoimg.setText("")
        self.twoimg.setIcon(QtGui.QIcon('image/boltsnumber/twoimg.png'))
        self.twoimg.setIconSize(QtCore.QSize(140, 140))
        self.twoimg.setObjectName("twoimg")
        self.twoimg_2 = QtWidgets.QPushButton(self.centralwidget)
        self.twoimg_2.setGeometry(QtCore.QRect(450, 100, 150, 150))
        self.twoimg_2.setText("")
        self.twoimg_2.setIcon(QtGui.QIcon('image/boltsnumber/twoimg_2.png'))
        self.twoimg_2.setIconSize(QtCore.QSize(140, 140))
        self.twoimg_2.setObjectName("twoimg_2")
        self.gridLayoutWidget_20 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_20.setGeometry(QtCore.QRect(610, 250, 141, 81))
        self.gridLayoutWidget_20.setObjectName("gridLayoutWidget_20")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.gridLayoutWidget_20)
        self.gridLayout_22.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget_20)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_22.addWidget(self.label_23, 0, 0, 1, 1)
        self.distance_a = QtWidgets.QLineEdit(self.gridLayoutWidget_20)
        self.distance_a.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.distance_a.setObjectName("distance_a")
        self.gridLayout_22.addWidget(self.distance_a, 2, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget_20)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_22.addWidget(self.label_25, 1, 0, 1, 1)
        self.pushResult_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushResult_2.setGeometry(QtCore.QRect(440, 350, 311, 32))
        self.pushResult_2.setObjectName("pushResult_2")
        self.textResult = QtWidgets.QLabel(self.centralwidget)
        self.textResult.setGeometry(QtCore.QRect(250, 440, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.textResult.setFont(font)
        self.textResult.setText("")
        self.textResult.setObjectName("textResult")
        self.gridLayoutWidget_9 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(450, 70, 301, 31))
        self.gridLayoutWidget_9.setObjectName("gridLayoutWidget_9")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gridLayoutWidget_9)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_20 = QtWidgets.QGridLayout()
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.radioButton = QtWidgets.QRadioButton(self.gridLayoutWidget_9)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_20.addWidget(self.radioButton, 0, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_20, 0, 0, 1, 1)
        self.gridLayout_23 = QtWidgets.QGridLayout()
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.radioButton_2 = QtWidgets.QRadioButton(self.gridLayoutWidget_9)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout_23.addWidget(self.radioButton_2, 0, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_23, 0, 1, 1, 1)
        boltsNumber.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(boltsNumber)
        self.statusbar.setObjectName("statusbar")
        boltsNumber.setStatusBar(self.statusbar)

        self.retranslateUi(boltsNumber)
        QtCore.QMetaObject.connectSlotsByName(boltsNumber)

    def retranslateUi(self, boltsNumber):
        _translate = QtCore.QCoreApplication.translate
        boltsNumber.setWindowTitle(_translate("boltsNumber", "Расчет количества болтов"))
        self.kH.setText(_translate("boltsNumber", "кН"))
        self.kgs.setText(_translate("boltsNumber", "кгс"))
        self.label_2.setText(_translate("boltsNumber", "Сумма толщин (см)"))
        self.label_3.setText(_translate("boltsNumber", "Диаметр болта"))
        self.label_4.setText(_translate("boltsNumber", "Кол. расчет. плоскостей"))
        self.label_5.setText(_translate("boltsNumber", "Класс прочности болта"))
        self.label_6.setText(_translate("boltsNumber", "Класс точности болта"))
        self.label_7.setText(_translate("boltsNumber", "Марка стали соед. элем."))
        self.label_8.setText(_translate("boltsNumber", "Необходимое"))
        self.label_9.setText(_translate("boltsNumber", "количество болтов"))
        self.pushResult.setText(_translate("boltsNumber", "Расчитать"))
        self.label.setText(_translate("boltsNumber", "Усилие действующее на болт"))
        self.label_10.setText(_translate("boltsNumber", "Несущая способность"))
        self.label_14.setText(_translate("boltsNumber", "Прочность"))
        self.label_15.setText(_translate("boltsNumber", "болта Nbs, Nbp"))
        self.label_18.setText(_translate("boltsNumber", "болтов Nb"))
        self.label_16.setText(_translate("boltsNumber", "Несущая способнсть"))
        self.label_24.setText(_translate("boltsNumber", "оси болтов (L, см)"))
        self.label_21.setText(_translate("boltsNumber", "Растояние до"))
        self.label_23.setText(_translate("boltsNumber", "Растояние между"))
        self.label_25.setText(_translate("boltsNumber", "болтами (a, см)"))
        self.pushResult_2.setText(_translate("boltsNumber", "Проверить несущую способность"))
        self.radioButton.setText(_translate("boltsNumber", "для двух болтов"))
        self.radioButton_2.setText(_translate("boltsNumber", "для трех болтов"))
        self.pushResult.setStyleSheet("""
                    QPushButton:hover { background-color: rgb(228, 228, 228) }
                    QPushButton:!hover { background-color: white }

                    QPushButton:pressed { background-color: rgb(191, 241, 255); }
                """)
        self.pushResult_2.setStyleSheet("""
                    QPushButton:hover { background-color: rgb(228, 228, 228) }
                    QPushButton:!hover { background-color: white }

                    QPushButton:pressed { background-color: rgb(191, 241, 255); }
                """)
        self.twoimg.setStyleSheet("""
                                                    QPushButton:hover { background-color: white }
                                                    QPushButton:!hover { background-color: white }

                                                    QPushButton:pressed { background-color: white; }
                                                """)
        self.twoimg_2.setStyleSheet("""
                                                    QPushButton:hover { background-color: white }
                                                    QPushButton:!hover { background-color: white }

                                                    QPushButton:pressed { background-color: white; }
                                                """)
        self.force.setValidator(QtGui.QDoubleValidator(0.0, 1000000.0, 3))
        self.tmin.setValidator(QtGui.QDoubleValidator(0.0, 1000000.0, 3))
        self.distance_l.setValidator(QtGui.QDoubleValidator(0.0, 1000000.0, 3))
        self.distance_a.setValidator(QtGui.QDoubleValidator(0.0, 1000000.0, 3))
