# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welding3.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_weldingFrame(object):
    def setupUi(self, weldingFrame):
        weldingFrame.setObjectName("weldingFrame")
        weldingFrame.resize(700, 500)
        weldingFrame.setMinimumSize(QtCore.QSize(700, 500))
        self.centralwidget = QtWidgets.QWidget(weldingFrame)
        self.centralwidget.setObjectName("centralwidget")
        self.frame1img = QtWidgets.QPushButton(self.centralwidget)
        self.frame1img.setGeometry(QtCore.QRect(40, 40, 230, 200))
        self.frame1img.setText("")
        self.frame1img.setIcon(QtGui.QIcon('image/frame/frame1img.png'))
        self.frame1img.setIconSize(QtCore.QSize(230, 200))
        self.frame1img.setObjectName("frame1img")
        self.frame2img = QtWidgets.QPushButton(self.centralwidget)
        self.frame2img.setGeometry(QtCore.QRect(40, 250, 230, 200))
        self.frame2img.setText("")
        self.frame2img.setIcon(QtGui.QIcon('image/frame/frame2img.png'))
        self.frame2img.setIconSize(QtCore.QSize(230, 200))
        self.frame2img.setObjectName("frame2img")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(290, 40, 101, 61))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 0, 1, 1, 1)
        self.rop = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.rop.setObjectName("rop")
        self.gridLayout_5.addWidget(self.rop, 1, 1, 1, 1)
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(490, 40, 161, 61))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 0, 1, 1, 1)
        self.weld_k = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.weld_k.setObjectName("weld_k")
        self.gridLayout_7.addWidget(self.weld_k, 1, 1, 1, 1)
        self.gridLayoutWidget_8 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(490, 110, 161, 61))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_8.addWidget(self.label_10, 0, 1, 1, 1)
        self.height = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.height.setObjectName("height")
        self.gridLayout_8.addWidget(self.height, 1, 1, 1, 1)
        self.pushResult = QtWidgets.QPushButton(self.centralwidget)
        self.pushResult.setGeometry(QtCore.QRect(290, 270, 371, 51))
        self.pushResult.setObjectName("pushResult")
        self.gridLayoutWidget_11 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_11.setGeometry(QtCore.QRect(290, 110, 101, 61))
        self.gridLayoutWidget_11.setObjectName("gridLayoutWidget_11")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.gridLayoutWidget_11)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_11.addWidget(self.label_14, 0, 1, 1, 1)
        self.mom = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.mom.setObjectName("mom")
        self.gridLayout_11.addWidget(self.mom, 1, 1, 1, 1)
        self.gridLayoutWidget_9 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(490, 180, 163, 61))
        self.gridLayoutWidget_9.setObjectName("gridLayoutWidget_9")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gridLayoutWidget_9)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_9.addWidget(self.label_11, 0, 1, 1, 1)
        self.force_l_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_9)
        self.force_l_2.setObjectName("force_l_2")
        self.gridLayout_9.addWidget(self.force_l_2, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 400, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(410, 410, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.result.setFont(font)
        self.result.setText("")
        self.result.setAlignment(QtCore.Qt.AlignCenter)
        self.result.setObjectName("result")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(490, 410, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(410, 40, 61, 61))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.kgs = QtWidgets.QRadioButton(self.gridLayoutWidget_4)
        self.kgs.setObjectName("kgs")
        self.gridLayout_4.addWidget(self.kgs, 0, 0, 1, 1)
        self.kn = QtWidgets.QRadioButton(self.gridLayoutWidget_4)
        self.kn.setObjectName("kn")
        self.gridLayout_4.addWidget(self.kn, 1, 0, 1, 1)
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(410, 110, 62, 61))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(290, 320, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(530, 330, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.result_2 = QtWidgets.QLabel(self.centralwidget)
        self.result_2.setGeometry(QtCore.QRect(460, 330, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.result_2.setFont(font)
        self.result_2.setText("")
        self.result_2.setAlignment(QtCore.Qt.AlignCenter)
        self.result_2.setObjectName("result_2")
        weldingFrame.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(weldingFrame)
        self.statusbar.setObjectName("statusbar")
        weldingFrame.setStatusBar(self.statusbar)

        self.retranslateUi(weldingFrame)
        QtCore.QMetaObject.connectSlotsByName(weldingFrame)

    def retranslateUi(self, weldingFrame):
        _translate = QtCore.QCoreApplication.translate
        weldingFrame.setWindowTitle(_translate("weldingFrame", "Проверка длины сварного шва"))
        self.label_7.setText(_translate("weldingFrame", "Реакция (R)"))
        self.label_9.setText(_translate("weldingFrame", "Катет шва (hш, см)"))
        self.label_10.setText(_translate("weldingFrame", "Высота балки (H, см)"))
        self.pushResult.setText(_translate("weldingFrame", "Расчитать длину сварного шва"))
        self.label_14.setText(_translate("weldingFrame", "Момент (М*см)"))
        self.label_11.setText(_translate("weldingFrame", "Толщина накладки (t, см)"))
        self.label.setText(_translate("weldingFrame", "Длина шва:"))
        self.label_5.setText(_translate("weldingFrame", "см"))
        self.kgs.setText(_translate("weldingFrame", "кгс"))
        self.kn.setText(_translate("weldingFrame", "кН"))
        self.label_2.setText(_translate("weldingFrame", "Ширина накладки:"))
        self.label_6.setText(_translate("weldingFrame", "см"))
        self.rop.setValidator(QtGui.QDoubleValidator(0.0, 1000000.0, 3))
        self.mom.setValidator(QtGui.QDoubleValidator(0.0, 1000000.0, 3))
        self.height.setValidator(QtGui.QDoubleValidator(0.0, 1000000.0, 3))
        self.weld_k.setValidator(QtGui.QDoubleValidator(0.0, 1000000.0, 3))
        self.force_l_2.setValidator(QtGui.QDoubleValidator(0.0, 1000000.0, 3))
        self.pushResult.setStyleSheet("""
                            QPushButton:hover { background-color: rgb(228, 228, 228) }
                            QPushButton:!hover { background-color: white }

                            QPushButton:pressed { background-color: rgb(191, 241, 255); }
                        """)
