# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welding2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_weldingFas2(object):
    def setupUi(self, weldingFas2):
        weldingFas2.setObjectName("weldingFas2")
        weldingFas2.resize(600, 450)
        weldingFas2.setMinimumSize(QtCore.QSize(600, 450))
        self.centralwidget = QtWidgets.QWidget(weldingFas2)
        self.centralwidget.setObjectName("centralwidget")
        self.fas1img = QtWidgets.QPushButton(self.centralwidget)
        self.fas1img.setGeometry(QtCore.QRect(50, 60, 200, 160))
        self.fas1img.setText("")
        self.fas1img.setIcon(QtGui.QIcon('image/fas2/fas1img.png'))
        self.fas1img.setIconSize(QtCore.QSize(170, 170))
        self.fas1img.setObjectName("fas1img")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(160, 20, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.fas2img = QtWidgets.QPushButton(self.centralwidget)
        self.fas2img.setGeometry(QtCore.QRect(330, 60, 200, 160))
        self.fas2img.setText("")
        self.fas2img.setIcon(QtGui.QIcon('image/fas2/fas2img.png'))
        self.fas2img.setIconSize(QtCore.QSize(155, 155))
        self.fas2img.setObjectName("fas2img")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(80, 220, 411, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(30, 250, 101, 61))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 0, 1, 1, 1)
        self.rop = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.rop.setObjectName("rop")
        self.gridLayout_5.addWidget(self.rop, 1, 1, 1, 1)
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(200, 250, 101, 61))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 0, 1, 1, 1)
        self.weld_l = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.weld_l.setObjectName("weld_l")
        self.gridLayout_6.addWidget(self.weld_l, 1, 1, 1, 1)
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(330, 250, 101, 61))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 0, 1, 1, 1)
        self.weld_k = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.weld_k.setObjectName("weld_k")
        self.gridLayout_7.addWidget(self.weld_k, 1, 1, 1, 1)
        self.gridLayoutWidget_8 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(460, 250, 111, 61))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_8.addWidget(self.label_10, 0, 1, 1, 1)
        self.force_l = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.force_l.setObjectName("force_l")
        self.gridLayout_8.addWidget(self.force_l, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(320, 340, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayoutWidget_9 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(370, 330, 81, 61))
        self.gridLayoutWidget_9.setObjectName("gridLayoutWidget_9")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gridLayoutWidget_9)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.result = QtWidgets.QLabel(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.result.setFont(font)
        self.result.setText("")
        self.result.setAlignment(QtCore.Qt.AlignCenter)
        self.result.setObjectName("result")
        self.gridLayout_9.addWidget(self.result, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(460, 340, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayoutWidget_10 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_10.setGeometry(QtCore.QRect(490, 330, 81, 61))
        self.gridLayoutWidget_10.setObjectName("gridLayoutWidget_10")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.gridLayoutWidget_10)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.ry_resist = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ry_resist.setFont(font)
        self.ry_resist.setText("")
        self.ry_resist.setAlignment(QtCore.Qt.AlignCenter)
        self.ry_resist.setObjectName("ry_resist")
        self.gridLayout_10.addWidget(self.ry_resist, 0, 0, 1, 1)
        self.pushResult = QtWidgets.QPushButton(self.centralwidget)
        self.pushResult.setGeometry(QtCore.QRect(190, 378, 110, 20))
        self.pushResult.setObjectName("pushResult")
        self.double = QtWidgets.QCheckBox(self.centralwidget)
        self.double.setGeometry(QtCore.QRect(180, 345, 160, 20))
        self.double.setObjectName("double")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(140, 250, 71, 61))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.kgs = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.kgs.setObjectName("kgs")
        self.gridLayout_2.addWidget(self.kgs, 0, 0, 1, 1)
        self.kn = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.kn.setObjectName("kn")
        self.gridLayout_2.addWidget(self.kn, 1, 0, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(30, 330, 150, 80))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.montage = QtWidgets.QRadioButton(self.gridLayoutWidget_4)
        self.montage.setObjectName("montage")
        self.gridLayout_4.addWidget(self.montage, 0, 0, 1, 1)
        self.prefab = QtWidgets.QRadioButton(self.gridLayoutWidget_4)
        self.prefab.setObjectName("prefab")
        self.gridLayout_4.addWidget(self.prefab, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 45, 60, 16))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(410, 45, 60, 16))
        self.label_3.setObjectName("label_3")
        weldingFas2.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(weldingFas2)
        self.statusbar.setObjectName("statusbar")
        weldingFas2.setStatusBar(self.statusbar)

        self.retranslateUi(weldingFas2)
        QtCore.QMetaObject.connectSlotsByName(weldingFas2)

    def retranslateUi(self, weldingFas2):
        _translate = QtCore.QCoreApplication.translate
        weldingFas2.setWindowTitle(_translate("weldingFas2", "Проверка длины сварного шва"))
        self.label_2.setText(_translate("weldingFas2", "Варианты сварного соединения"))
        self.label_6.setText(_translate("weldingFas2", "Проверка несущей способности сварного шва"))
        self.label_7.setText(_translate("weldingFas2", "Реакция (R)"))
        self.label_8.setText(_translate("weldingFas2", "Длина (Lш, см)"))
        self.label_9.setText(_translate("weldingFas2", "Катет шва (см)"))
        self.label_10.setText(_translate("weldingFas2", "Плече (L, см)"))
        self.label_11.setText(_translate("weldingFas2", "Tш="))
        self.label_13.setText(_translate("weldingFas2", "<="))
        self.pushResult.setText(_translate("weldingFas2", "Расчитать"))
        self.kgs.setText(_translate("weldingFas2", "кгс"))
        self.kn.setText(_translate("weldingFas2", "кН"))
        self.montage.setText(_translate("weldingFas2", "Монтажный шев"))
        self.prefab.setText(_translate("weldingFas2", "Заводской шев"))
        self.label.setText(_translate("weldingFas2", "R<=3т"))
        self.label_3.setText(_translate("weldingFas2", "R<=5т"))
        self.double.setText(_translate("weldingFas2", "Ответная планка"))
        self.rop.setValidator(QtGui.QDoubleValidator(0.0, 1000000.0, 3))
        self.weld_l.setValidator(QtGui.QDoubleValidator(0.0, 1000000.0, 3))
        self.weld_k.setValidator(QtGui.QDoubleValidator(0.0, 1000000.0, 3))
        self.force_l.setValidator(QtGui.QDoubleValidator(0.0, 1000000.0, 3))
        self.pushResult.setStyleSheet("""
                            QPushButton:hover { background-color: rgb(228, 228, 228) }
                            QPushButton:!hover { background-color: white }

                            QPushButton:pressed { background-color: rgb(191, 241, 255); }
                        """)

